obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
#Begin [0016004715 add the kernel power code,20180316]
obj-$(CONFIG_ZTEMT_POWER_DEBUG)	+= ztemt_power_debug/
#End   [0016004715 add the kernel power code,20180316]
