### common file
obj-$(CONFIG_NUBIA_SENSORS)                             += sensor_common.o

#---------------------------PS and Light SENSOR----------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_STK3337)                     += stk3337/

